development:
  adapter: postgresql
  encoding: unicode
  database: student_project_one
  pool: 5
  username: postgres
  password: blealf92

test:
  adapter: postgresql
  encoding: unicode
  database: student_project_one
  pool: 5
  username: postgres
  password: blealf92